### ISSUE TITLE
Overlay simple geospacial data over the map

### ISSUE THREAD

**Issue by petarpenkov** [cs210/orbit-code#2]
Add any form of shape on the map depending on the data. Point is to get started with any geojson data.

Data display options: points, heat map

**Comment by juliatruitt** [comment]
Added heatmap data visualization that you can toggle on and off with a button in the top left corner of the screen. This heatmap functionality is currently just displaying dummy data points around San Francisco. Users can also drag and drop a GeoJSON file onto the map, and the map will display each data point. To best view this functionality, zoom the map way out, since it's currently zoomed in to see the data points around SF.

Waiting on @rebeccabauer to integrate this functionality with real data.
